package com.garpr.android.misc;


public final class Constants {


    public static final int TWITTER_LENGTH = 140;

    public static final String ABOUT_URL = "http://www.garpr.com/#/about";
    public static final String API_URL = "http://api.garpr.com";
    public static final String CHARLES_TWITTER_URL = "https://twitter.com/charlesmadere";
    public static final String COMPLETED = "completed";
    public static final String CURRENT_ACTIVITY = "current_activity";
    public static final String DATE = "date";
    public static final String DAY_OF_MONTH_FORMAT = "d";
    public static final String DEBUG = "debug";
    public static final String DISPLAY_NAME = "display_name";
    public static final String EASTER_EGG = "easter_egg";
    public static final String ERROR = "error";
    public static final String EXCEPTION = "exception";
    public static final String EXCEPTION_LOCATION = "exception_location";
    public static final String EXCEPTION_MESSAGE = "exception_message";
    public static final String FALSE = "false";
    public static final String FAIL = "fail";
    public static final String FAILURE = "failure";
    public static final String FIRST_SYNC = "first_sync";
    public static final String GAME = "game";
    public static final String GITHUB_URL = "https://github.com/airokay/smash-ranks-android";
    public static final String HEAD_TO_HEAD = "head_to_head";
    public static final String ID = "id";
    public static final String IVAN_TWITTER_URL = "https://twitter.com/garsh0p";
    public static final String JSON = "json";
    public static final String LAST_SYNC = "last_sync";
    public static final String LOSE = "lose";
    public static final String LOSER_ID = "loser_id";
    public static final String LOSER_NAME = "loser_name";
    public static final String LOSS = "loss";
    public static final String LOSSES = "losses";
    public static final String MATCH = "match";
    public static final String MATCHES = "matches";
    public static final String MESSAGE = "message";
    public static final String MIMETYPE_TEXT_PLAIN = "text/plain";
    public static final String MM_DD_YY_FORMAT = "M/d/yy";
    public static final String MONTH_FORMAT = "LLLL";
    public static final String MONTH_AND_DAY_FORMAT = "MMM d";
    public static final String MONTH_AND_DAY_AND_YEAR_FORMAT = "MMM d, yyyy";
    public static final String NAME = "name";
    public static final String NEW_REGION = "new_region";
    public static final String NEW_ROSTER = "new_roster";
    public static final String NORCAL = "norcal";
    public static final String NULL = "null";
    public static final String OLD_REGION = "old_region";
    public static final String ONBOARDING = "onboarding";
    public static final String ONBOARDING_ALREADY_COMPLETED = "onboarding_already_completed";
    public static final String ONBOARDING_STATUS = "onboarding_status";
    public static final String OPPONENT = "opponent";
    public static final String OPPONENT_ID = "opponent_id";
    public static final String OPPONENT_NAME = "opponent_name";
    public static final String ORB = "orb";
    public static final String PERIODIC_SYNC = "periodic_sync";
    public static final String PLAYER = "player";
    public static final String PLAYER_ID = "player_id";
    public static final String PLAYER_1_ID = "player_1_id";
    public static final String PLAYER_2_ID = "player_2_id";
    public static final String PLAYER_HEAD_TO_HEAD = "player_head_to_head";
    public static final String PLAYER_MATCHES = "player_matches";
    public static final String PLAYER_NAME = "player_name";
    public static final String PLAYERS = "players";
    public static final String RANK = "rank";
    public static final String RANKING = "ranking";
    public static final String RANKINGS = "rankings";
    public static final String RANKINGS_DATE_FORMAT = "yyyy-MM-dd HH:mm:ss.SSSSSS";
    public static final String RATING = "rating";
    public static final String REGION = "region";
    public static final String REGION_CHANGE = "region_change";
    public static final String REGION_ID = "region_id";
    public static final String REGION_NAME = "region_name";
    public static final String REGIONS = "regions";
    public static final String RESULT = "result";
    public static final String SAME_ROSTER = "same_roster";
    public static final String SETTINGS = "settings";
    public static final String SHARE = "share";
    public static final String SKIPPED = "skipped";
    public static final String SKIPPED_ONBOARDING = "skipped_onboarding";
    public static final String STATUS = "status";
    public static final String SYNC = "sync";
    public static final String SYNC_RESULT = "sync_result";
    public static final String TIME = "time";
    public static final String TOURNAMENT = "tournament";
    public static final String TOURNAMENTS = "tournaments";
    public static final String TOURNAMENT_DATE = "tournament_date";
    public static final String TOURNAMENT_DATE_FORMAT = "MM/dd/yy";
    public static final String TOURNAMENT_ID = "tournament_id";
    public static final String TOURNAMENT_NAME = "tournament_name";
    public static final String TRUE = "true";
    public static final String WEB_URL = "http://garpr.com/#/";
    public static final String WHAT = "what";
    public static final String WHICH = "which";
    public static final String WHO = "who";
    public static final String WIN = "win";
    public static final String WINNER_ID = "winner_id";
    public static final String WINNER_NAME = "winner_name";
    public static final String WINS = "wins";
    public static final String YEAR_FORMAT = "yyyy";

    public static final String[] RANDOM_YOUTUBE_VIDEOS = {
            "https://www.youtube.com/watch?v=pD_imYhNoQ4", // wombo combo
            "https://www.youtube.com/watch?v=rZIxUjct3uo", // axe vs silentwolf evo 2014
            "https://www.youtube.com/watch?v=jcfv63Xvs5c", // mango vs leffen apex 2014
            "https://www.youtube.com/watch?v=Qna80MbcAAc", // m2k vs shiz RoM
            "https://www.youtube.com/watch?v=WqWFYOxjZ54", // pure pwnage episode 1
            "https://www.youtube.com/watch?v=xRitJ1m8E1w", // the human abstract - patterns
            "https://www.youtube.com/watch?v=Al_0TsWKtZk", // chillin' at charles crew battle
            "https://www.youtube.com/watch?v=HkzMA1jrm00", // austin powers blackjack scene
            "https://www.youtube.com/watch?v=IFlfHC1Rr8E", // bizzarro flame's up tilt kill KoC 4
            "https://www.youtube.com/watch?v=SDnKE5J7ki8", // m2k vs amsa KoC 4
            "https://www.youtube.com/watch?v=UVJK98U99ZY", // algerian DI
            "https://www.youtube.com/watch?v=ZRbDl3duEqQ", // luigi was pissed today
            "https://www.youtube.com/watch?v=me45kHEy10A", // scott pilgrim with british accents
            "https://www.youtube.com/watch?v=WNr5Ts-oaj0", // westballz vs eddy mexico SSS
            "https://www.youtube.com/watch?v=NB2klN3Tiog", // hbox vs javi Forte 2
            "https://www.youtube.com/watch?v=DQ4AhCW5-IA", // the greatest thing ever said
            "https://www.youtube.com/watch?v=NSf2mgkRm7Q", // documentary episode 1
            "https://www.youtube.com/watch?v=kmyJUtzkKy4", // boot stomp
            "https://www.youtube.com/watch?v=t5a4fZTNal8", // btbam - lay your ghosts to rest
            "https://www.youtube.com/watch?v=QKfGNdSxy5E", // lord vs s2j falcon round robin
            "https://www.youtube.com/watch?v=U3mtUCizvf8", // ahmad vs gar money match
            "https://www.youtube.com/watch?v=lSxYS99TwaU", // fly vs silentwolf KoC 3
            "https://www.youtube.com/watch?v=7i0PUCX7VEw", // leffen vs chillin salty suite
            "https://www.youtube.com/watch?v=MlGM0BFv3JU", // westballz sacred combo
            "https://www.youtube.com/watch?v=4Ogs89Ok9CY" // mango vs armada im not yelling
    };


}
