package com.garpr.android.models2;


import android.os.Parcel;
import android.os.Parcelable;

import com.garpr.android.misc.Constants;
import com.garpr.android.misc.ListUtils.AlphabeticallyComparable;
import com.garpr.android.misc.Utils;

import org.json.JSONException;
import org.json.JSONObject;


public class Player implements AlphabeticallyComparable, Parcelable {


    private final Ranking mRanking;
    private final String mId;
    private final String mName;




    public Player(final JSONObject json) throws JSONException {
        this(json, null);
    }


    public Player(final JSONObject json, final Ranking ranking) throws JSONException {
        mId = Utils.getJSONString(json, Constants.OPPONENT_ID, Constants.ID);
        mName = Utils.getJSONString(json, Constants.OPPONENT_NAME, Constants.NAME);
        mRanking = ranking;
    }


    private Player(final Parcel source) {
        mRanking = source.readParcelable(Ranking.class.getClassLoader());
        mId = source.readString();
        mName = source.readString();
    }


    @Override
    public boolean equals(final Object o) {
        final boolean isEqual;

        if (this == o) {
            isEqual = true;
        } else if (o instanceof Player) {
            final Player p = (Player) o;

            if (mId.equals(p.getId()) && mName.equals(p.getName())) {
                if (hasRanking() && p.hasRanking()) {
                    isEqual = mRanking.equals(p.getRanking());
                } else if (!hasRanking() && !p.hasRanking()) {
                    isEqual = true;
                } else {
                    isEqual = false;
                }
            } else {
                isEqual = false;
            }
        } else {
            isEqual = false;
        }

        return isEqual;
    }


    @Override
    public char getFirstCharOfName() {
        return mName.charAt(0);
    }


    public String getId() {
        return mId;
    }


    public String getName() {
        return mName;
    }


    public Ranking getRanking() {
        return mRanking;
    }


    @Override
    public int hashCode() {
        // this method was automatically generated by Android Studio

        int result = mRanking != null ? mRanking.hashCode() : 0;
        result = 31 * result + mId.hashCode();
        result = 31 * result + mName.hashCode();

        return result;
    }


    public boolean hasRanking() {
        return mRanking != null;
    }


    @Override
    public String toString() {
        return getName();
    }




    /*
     * Code necessary for the Android Parcelable interface is below. Read more here:
     * https://developer.android.com/intl/es/reference/android/os/Parcelable.html
     */


    @Override
    public int describeContents() {
        return 0;
    }


    @Override
    public void writeToParcel(final Parcel dest, final int flags) {
        dest.writeParcelable(mRanking, flags);
        dest.writeString(mId);
        dest.writeString(mName);
    }


    public static final Creator<Player> CREATOR = new Creator<Player>() {
        @Override
        public Player createFromParcel(final Parcel source) {
            return new Player(source);
        }


        @Override
        public Player[] newArray(final int size) {
            return new Player[size];
        }
    };


}
