package com.garpr.android.models2;


import android.content.Context;
import android.os.Parcel;
import android.os.Parcelable;

import com.garpr.android.App;
import com.garpr.android.R;
import com.garpr.android.misc.Constants;

import org.json.JSONException;
import org.json.JSONObject;


public class Ranking implements Parcelable {


    private final float mRating;
    private final int mRank;




    public Ranking(final JSONObject json) throws JSONException {
        mRating = (float) json.getDouble(Constants.RATING);
        mRank = json.getInt(Constants.RANK);
    }


    private Ranking(final Parcel source) {
        mRating = source.readFloat();
        mRank = source.readInt();
    }


    @Override
    @SuppressWarnings("CloneDoesntDeclareCloneNotSupportedException")
    public Ranking clone() {
        try {
            return (Ranking) super.clone();
        } catch (final CloneNotSupportedException e) {
            throw new IllegalStateException(e);
        }
    }


    @Override
    public boolean equals(final Object o) {
        final boolean isEqual;

        if (this == o) {
            isEqual = true;
        } else if (o instanceof Ranking) {
            final Ranking r = (Ranking) o;
            isEqual = mRating == r.getRating() && mRank == r.getRank();
        } else {
            isEqual = false;
        }

        return isEqual;
    }


    public int getRank() {
        return mRank;
    }


    public float getRating() {
        return mRating;
    }


    @Override
    public int hashCode() {
        // this method was automatically generated by Android Studio

        int result = (mRating != +0.0f ? Float.floatToIntBits(mRating) : 0);
        result = 31 * result + mRank;

        return result;
    }


    @Override
    public String toString() {
        final Context context = App.getContext();
        return context.getString(R.string.rank_x_rating_y, mRank, mRating);
    }




    /*
     * Code necessary for the Android Parcelable interface is below. Read more here:
     * https://developer.android.com/intl/es/reference/android/os/Parcelable.html
     */


    @Override
    public int describeContents() {
        return 0;
    }


    @Override
    public void writeToParcel(final Parcel dest, final int flags) {
        dest.writeFloat(mRating);
        dest.writeInt(mRank);
    }


    public static final Creator<Ranking> CREATOR = new Creator<Ranking>() {
        @Override
        public Ranking createFromParcel(final Parcel source) {
            return new Ranking(source);
        }


        @Override
        public Ranking[] newArray(final int size) {
            return new Ranking[size];
        }
    };


}
